'use strict';
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),native=path.join(root,'native');
execFileSync(process.execPath,['scripts/build.cjs'],{cwd:root,stdio:'inherit'});
for(const name of ['index.html','app.css','app.js','OPPOSans-Regular.woff2'])fs.copyFileSync(path.join(root,'dist',name),path.join(native,'web',name));
fs.copyFileSync(path.join(root,'THIRD_PARTY_NOTICES.md'),path.join(native,'web','THIRD_PARTY_NOTICES.txt'));
fs.mkdirSync(path.join(root,'release'),{recursive:true});
execFileSync('go',['run','github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.5.0','-64','-manifest','cmd/serial-assistant/app.manifest','-file-version','0.1.4.0','-product-version','0.1.4','-product-name','SerialAssistant','-description','串口助手','-original-name','SerialAssistant-0.1.4-win-x64.exe','-propagate-ver-strings','-o','cmd/serial-assistant/resource_windows_amd64.syso','versioninfo.json'],{cwd:native,stdio:'inherit'});
const artifact=path.join(root,'release','SerialAssistant-0.1.4-win-x64.exe');
execFileSync('go',['build','-buildvcs=false','-trimpath','-ldflags=-s -w -H windowsgui','-o',artifact,'./cmd/serial-assistant'],{cwd:native,stdio:'inherit',env:{...process.env,GOOS:'windows',GOARCH:'amd64',CGO_ENABLED:'0'}});
console.log('Single-file Windows EXE: '+(fs.statSync(artifact).size/1048576).toFixed(2)+' MiB');
